OPENAI_API_KEY = "sk-FxBXmoohg6JiMObXIJ6Z_N4rSwOLKO-PWlWAa8U78UT3BlbkFJgEMyyQ9nMZLAhVtrTO6eGJBFOkvXVXLTD1UpFv4kUA"
OPENAI_MODEL="gpt-4"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_TRACING_V2=true
PINECONE_API_KEY="a2a08fb6-dbff-459d-9f99-dc48b0b7cbdd"
VOYAGE_API_KEY="pa-qbi_fEnxfkEZCZE413EphdZ7sxHzsH_yDtY7ITjiNKY"
NEO4J_URI="neo4j+s://fd9b4141.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="UR3otV-Oym4Kr_kTGSLBNGcN5GZmmbvZtlRIXeGyyHs"
NEO4J_DATABASE="neo4j"
TAVILY_API_KEY = "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"
SERPER_API_KEY="2ad1303bc177bd9471b68fdd6945e383aec96044"

